# Generated by Django 4.2.2 on 2023-06-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_products_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
